#include "rwmake.ch"        // incluido pelo assistente de conversao do AP5 IDE em 03/07/01

User Function axse5()        // incluido pelo assistente de conversao do AP5 IDE em 03/07/01

//AOA - 03/07/2019 - Descontinuado a rotina para evitar problema de exclusão de movimento bancario.
MsgStop( 'Rorina descontinuada!',"HLB BRASIL" )
Return

axcadastro("SE5","Manutencao Cadastro de Naturezas",".t.",".t.")

Return(nil)        // incluido pelo assistente de conversao do AP5 IDE em 03/07/01

