
/*
Funcao      : BRWD1001
Parametros  : Nenhum
Retorno     : Nenhum   
Objetivos   : AxCadastro tabela SZ3 - Linha de produto
Autor     	: 
Data     	:  
Obs         : 
TDN         : 
Revisão     : Tiago Luiz Mendonça 
Data/Hora   : 15/03/2012
Módulo      : Gestão Pessoal
Cliente     : Tellabs
*/

*-------------------------*
 User Function BRWD1001()
*-------------------------*
	
	AxCadastro("SZ3","Linha de Produto",".T.",".T.")

Return